    - name: Commit dan Push Jika Ada Perubahan
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.mpd
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update index.mpd [$(date)]" && git push)
        
